### PR TITLE
Error handling Fix

### PR DESCRIPTION
**Pull request by arturbeg**

### CODE REVIEW

**Review by Sol3iman — APPROVED** [review]
These changes are live in the production UI. 
Goerli uses mainnet error decoding and localhost UI testing is done on Goerli so no changes needed. Approved.

**Review by CyclopsRex — COMMENTED** [review]
Sorry, just seen review request. My comments:
- don't understand why other networks do not need changed. If we don't support WalletConnect on kovan and localhost blockchains (or if we no longer want to support those blockchains at all) then that probably deserved a code comment and/or some documentation
- Not important, but it would be tidier to use `else if { ... } else { ... }` instead of `else { if { ... } else {...}}`

**Comment by Sol3iman** [comment]
> 

Kovan is no longer being supported so we would have no reason to go back to that network => we can probably comment this error handling out. 
Localhost UI: I don't know why this was there in the first place given that we always use a testnet for local UI instances. 
wdyt @arturbeg ?

**Comment by CyclopsRex** [comment]
Didn't realise kovan was not being supported for testing any more. What is we want to test Aave or some other project that's not available on goerli?

FWIW, I sometimes use a local blockchain rather than the testnet for my UI instances (means I can fast forward time, change data, get a reproducable state, etc.). But I don't think this counts for much as I don't do much UI work, so it matters more what the rest of the team do.

I'd be totally fine with a policy of "we only support walletconnect on mainnet & on goerli", especially if we think the work to add support would be different from mainnet. But we should be clear in our own minds, and maybe in code comments, what our policy is for other networks.

**Comment by arturbeg** [comment]
@Sol3iman i think worth fixing localhost and kovan for completeness as i don't think that'd be time consuming, do you wanna pick this up?

**Comment by arturbeg** [comment]
lemme merge this change now and we can do it in a separate PR

**Pull request merged**
